# Generated by Django 4.1.7 on 2023-03-03 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_create_room_model"),
        ("users", "0001_create_users_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start_at", models.DateField()),
                ("date_end_at", models.DateField()),
                (
                    "guest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="room.room"),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
            },
        ),
    ]
