# Generated by Django 4.1.7 on 2023-02-26 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_create_model_room"),
        ("users", "0001_create_user_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_on", models.DateField()),
                ("date_off", models.DateField()),
                (
                    "guest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
            },
        ),
    ]
