# Generated by Django 4.1.7 on 2023-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("places", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "number",
                "verbose_name_plural": "numbers",
            },
        ),
    ]
